## scikit learn을 이용하여 붓꽃(lris)데이터 품종 예측하기

In [1]:
import sklearn

## 붓꽃 예측을 위한 사이킷런 필요 모듈 로딩


In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

##  데이터 세트를 로딩

In [4]:
import pandas as pd

# iris 로딩
iris = load_iris()

# iris.data는 iris 데이터 set에서 피처만으로 된 데이터를 numpy로 가짐
iris_data = iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블 데이터를 numpy로  가지고 있음
iris_label = iris.target
print("target값", iris_label)
print("target명:", iris.target_names)

# 붓꽃 데이터세트를 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

target값 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

## train, test split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(iris_df, iris_label, test_size=0.2, random_state=42)

In [6]:
# train 수행
# DecisionTreeClassifier
dt_clf = DecisionTreeClassifier()

# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [8]:
# test 세트로 예측(Predict)수행
pred = dt_clf.predict(X_test)

In [9]:
pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [13]:
# 예측 정확도 평가
from sklearn.metrics import accuracy_score
print("예측 정확도: {0: .2f}".format(accuracy_score(y_test, pred)))

예측 정확도:  1.00


## 사이킷런 내장 예제 데이터

In [14]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [15]:
keys = iris_data.keys()
print("붓꽃 데이터셋의 키값들", keys)
# data는 피처의 데이터 셋을 가리킴
# target은 분류 시 레이블값, 회귀일때는 숫자 결과값 데이터셋
# target_names는 개별 레이블의 이름
# feature_names는 피처의 이름을 나타냄
# DESCR은 데이터 세트에 대한 설명과 각 피처의 설명

붓꽃 데이터셋의 키값들 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


## 교차 검증

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
labels = iris.target
dt_clf = DecisionTreeClassifier(random_state=121)

# 5개의 폴드 세트로 분리하는  KFold 객체와 폴드 세트별 정확도를 담은 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print("붓꽃 데이터 세트 크기", features.shape)

붓꽃 데이터 세트 크기 (150, 4)


In [24]:
features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [25]:
n_iter = 0

# KFold 객체의 split() 호츨하면 폴드 별 학습용, 검증용 테스트의 경우 로우 인덱스를 array로 변환
for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]

    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    # 반복시 마다 정확도 측정
    acc = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    print("\n{0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증데이터 크기: {3}".format(n_iter, acc, train_size, test_size))
    print('{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))

    cv_accuracy.append(acc)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print("\n 평균 검증 정확도", np.mean(cv_accuracy))


1 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증데이터 크기: 30
1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

2 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증데이터 크기: 30
2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

3 교차 검증 정확도: 0.9, 학습 데이터 크기: 120, 검증데이터 크기: 30
3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

4 교차 검증 정확도: 0.9333, 학습 데이터 크기: 120, 검증데이터 크기: 30
4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

5 교차 검증 정확도: 0.7333, 학습 데이터 크기: 120, 검증데이터 크기: 30
5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

 평균 검증 정확도 0.91332


In [28]:
# cross - val - score
from sklearn.model_selection import cross_val_score

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
labels = iris_data.target

# 성능 지표는 정확도, 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, labels, cv=3, scoring='accuracy')

print("교차 검증별 정확도", np.round(scores, 4))
print("평균 검증 정확도", np.round(np.mean(scores), 4))

교차 검증별 정확도 [0.98 0.94 0.98]
평균 검증 정확도 0.9667


In [31]:
# Grid Search CV
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습데이터와 테스트 데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

## param 들을 dict 형태로 설정
param = {'Max_depth': [1,2,3], 'Min_sample_split': [2,3]}

In [ ]:
import pandas as pd

# param_grid의 하이퍼파라미터들을 3개의 train, test, set fold 로 나누어서 테스트 수행
# refit=True가 default True면 가장 좋은 파라미터 재학습

grid_tree = GridSearchCV(dtree, param_grid = param, cv=3, refit=True, return_train_score=True)

grid_tree.fit(X_train, y_train)

## 데이터 전처리
* 데이터 클린징
* 결손값(Null/NaN)처리
* 데이터 인코딩(레이블, 원핫 인코딩)
* 데이터 스케일링
* 이상치 제거
* Feature선택, 추출 및 가공

In [32]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고', '전자렌지', '컴퓨터', '선풍기','선풍기', '믹서', '믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 label 인코딩 수행.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("인코딩 변환값", labels)

인코딩 변환값 [0 1 4 5 3 3 2 2]


In [33]:
print("인코딩 클래스", encoder.classes_)

인코딩 클래스 ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [35]:
item = np.array(items).reshape(-1, 1)
item.shape

(8, 1)

In [36]:
# 원 핫 인코딩
from sklearn.preprocessing import OneHotEncoder

# 2차원 ndarray로 변환
item = np.array(items).reshape(-1, 1)

# One-Hot Encoder 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(item)
oh_labels = oh_encoder.transform(item)

# OneHotEncoder로 변환한 결과는 Sparse 행렬이므로 Dense형태로 변환
print("원-핫 인코딩 데이터")
print(oh_labels.toarray())
print("원-핫 인코딩 데이터 차원")
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [37]:
pd = pd.DataFrame(oh_labels)
pd

0
0  <Compressed Sparse Row sparse matrix of dtype 'float64'\n\twith 1 stored elements and shape (1, 6)>\n  Coords\tValues\n  (0, 0)\t1.0
1  <Compressed Sparse Row sparse matrix of dtype 'float64'\n\twith 1 stored elements and shape (1, 6)>\n  Coords\tValues\n  (0, 1)\t1.0
2  <Compressed Sparse Row sparse matrix of dtype 'float64'\n\twith 1 stored elements and shape (1, 6)>\n  Coords\tValues\n  (0, 4)\t1.0
3  <Compressed Sparse Row sparse matrix of dtype 'float64'\n\twith 1 stored elements and shape (1, 6)>\n  Coords\tValues\n  (0, 5)\t1.0
4  <Compressed Sparse Row sparse matrix of dtype 'float64'\n\twith 1 stored elements and shape (1, 6)>\n  Coords\tValues\n  (0, 3)\t1.0
5  <Compressed Sparse Row sparse matrix of dtype 'float64'\n\twith 1 stored elements and shape (1, 6)>\n  Coords\tValues\n  (0, 3)\t1.0
6  <Compressed Sparse Row sparse matrix of dtype 'float64'\n\twith 1 stored elements and shape (1, 6)>\n  Coords\tValues\n  (0, 2)\t1.0
7  <Compressed Sparse Row sparse matrix of dtype 'float64'\n\twith 1 stored elements and shape (1, 6)>\n  Coords\tValues\n  (0, 2)\t1.0

## 피처 스케일링

In [38]:
# StandardScaler: 평균이 0이고 분산이 1인 정규 분포 형태로 변환
# MinMaxScaler: 데이터 값을 0과 1사이의 범위 값으로 변환

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print("feature 들의 평균 값")
print(iris_df.mean())
print("feature들의 분산 값")
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [39]:
# StandardScaler

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print("평균 값")
print(iris_df_scaled.mean())
print("분산 값")
print(iris_df_scaled.var())

평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [40]:
# MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_df_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_df_scaled, columns=iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64
sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64


In [41]:
# train일때만 fit_transform
# test는 transform만
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(train_array)
test_scaled = scaler.transform(test_array)

print("원본 train_array", train_array)
print("scaled train_array", train_scaled)

print("원본 test_array", test_array)
print("scaled test_array", test_scaled)

원본 train_array [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
scaled train_array [[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]
 [0.7]
 [0.8]
 [0.9]
 [1. ]]
원본 test_array [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
scaled test_array [[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]]
