## Numpy 기초

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("1차원",arr1)
print("2차원", arr2)

1차원 [1 2 3]
2차원 [[1 2 3]
 [4 5 6]]


In [3]:
list1 = [1, 2, 3]
print("list type", type(list1))
array1 = np.array(list1)
print("array type", type(array1))
print("array shape", array1.shape)

array2 = np.array([[1,2,3],
                   [4,5,6]])
print("array type", type(array2))
print("array shape", array2.shape)

array3 = np.array([[1,2,3]])
print("array type", type(array3))
print("array shape", array3.shape)

list type <class 'list'>
array type <class 'numpy.ndarray'>
array shape (3,)
array type <class 'numpy.ndarray'>
array shape (2, 3)
array type <class 'numpy.ndarray'>
array shape (1, 3)


## ndarray의 데이터 타입

In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1 , array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
list2 = [1, 2, 'test']
print(type(list2))
array2 = np.array(list2)
print(type(array2))
print(array2 , array2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' 'test'] <U11


In [8]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype(float)
print("array_float: ", array_float, array_float.dtype)

array_float:  [1. 2. 3.] float64


In [10]:
array_int = array_float.astype(int)
print("array_int: ", array_int, array_int.dtype)

array_int:  [1 2 3] int32


## ndarray를 편하게 생성하기 - arange, zeros, ones

In [11]:
sequence_array = np.arange(10)
print("sequence_array: ", sequence_array)
print(sequence_array.dtype, sequence_array.shape)

sequence_array:  [0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [13]:
#(3, 2) shape을 가지는 모든 원소가 0, dtype은 int32 인 ndarray 생성
zeros_arr = np.zeros((3,2), dtype='int32')
print(zeros_arr)
print(zeros_arr.dtype, zeros_arr.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [14]:
# (3, 2) shape을 가지는 모든 원소가 1인 ndarray 생성
ones_arr = np.ones((3,2))
print(ones_arr)
print(ones_arr.dtype, ones_arr.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape

In [15]:
array1 = np.arange(10)
print(array1)

# (2, 5) shape으로 변환
array2 = array1.reshape(2,5)
print(array2)

# (5, 2) shape으로 변환
array3 = array1.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print(array2)

array3 = array1.reshape(5, -1)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## numpy ndarray의 데이터 세트 선택하기 - indexing

In [3]:
# 1에서 부터 9까지의 1차원 ndarray생성
array1 = np.arange(start=1, stop=10)
print(array1)

# index 0 ~ array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print(value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>


In [4]:
print("맨 뒤의 값", array1[-1], "맨 뒤의 두번째 값", array1[-2])

맨 뒤의 값 9 맨 뒤의 두번째 값 8


In [5]:
array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [6]:
array1d = np.arange(start = 1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값: ', array2d[0,0])
print('(row=0, col=1) index 가리키는 값: ', array2d[0,1])
print('(row=1, col=0) index 가리키는 값: ', array2d[1,0])
print('(row=2, col=2) index 가리키는 값: ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값:  1
(row=0, col=1) index 가리키는 값:  2
(row=1, col=0) index 가리키는 값:  4
(row=2, col=2) index 가리키는 값:  9


In [8]:
array1 = np.arange(start=1, stop=10)
print('array1: ', array1)
array3 = array1[0:3]
print('array3', array3)
print(type(array3))
print(array3.shape)

array1:  [1 2 3 4 5 6 7 8 9]
array3 [1 2 3]
<class 'numpy.ndarray'>
(3,)


In [12]:
array1 = np.arange(start=1, stop=10)
# 0-2(2포함)까지 추출
array4 = array1[:3]
print('array4', array4)

# 위치 인덱스 3부터 마지막 추출
array5 = array1[3:]
print('array5', array5)

# 위치 인덱스 전체 추출
array6 = array1[:]
print('array6', array6)

array4 [1 2 3]
array5 [4 5 6 7 8 9]
array6 [1 2 3 4 5 6 7 8 9]


In [18]:
# 펜시 인덱싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0,1], 2]
print('array3', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array4', array4.tolist())

array5 = array2d[[0,1]]
print('array5', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array3 [3, 6]
array4 [[1, 2], [4, 5]]
array5 [[1, 2, 3], [4, 5, 6]]


In [19]:
#불린 인덱싱
array1d = np.arange(start=1, stop=10)
print(array1d)
# [] 안에 array1d > 5 boolean indexing을 적용
array3 = array1d[array1d > 5]
print('불린 인덱스값', array3)

[1 2 3 4 5 6 7 8 9]
불린 인덱스값 [6 7 8 9]


## 행렬의 정렬 - sort() 와 argsort()

In [20]:
org_array = np.array([3, 1, 9, 5])
print("원본 행렬", org_array)

# np.sort()
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬', sort_array1)
print('np.sort() 호출 후 원본 배열', org_array)

# ndarray.sort()
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 배열', sort_array2)
print('원본 배열', org_array)

원본 행렬 [3 1 9 5]
np.sort() 호출 후 반환된 정렬 [1 3 5 9]
np.sort() 호출 후 원본 배열 [3 1 9 5]
org_array.sort() 호출 후 반환된 배열 None
원본 배열 [1 3 5 9]


In [22]:
sort_array1_desc = np.sort(org_array)[::-1]
print("내림차순으로 정렬", sort_array1_desc)

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(sort_indices) # 행렬 정렬시 배열의 인덱스값 추출

내림차순으로 정렬 [9 5 3 1]
[1 0 3 2]


In [26]:
name_array = np.array(['john', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print("성적 오름차순 성적 인덱스", sort_indices_asc)
print("성적 오름차순 이름 출력", name_array[sort_indices_asc])

성적 오름차순 성적 인덱스 [0 2 4 1 3]
성적 오름차순 이름 출력 ['john' 'Sarah' 'Samuel' 'Mike' 'Kate']
