## Numpy 기초

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("1차원",arr1)
print("2차원", arr2)

1차원 [1 2 3]
2차원 [[1 2 3]
 [4 5 6]]


In [3]:
list1 = [1, 2, 3]
print("list type", type(list1))
array1 = np.array(list1)
print("array type", type(array1))
print("array shape", array1.shape)

array2 = np.array([[1,2,3],
                   [4,5,6]])
print("array type", type(array2))
print("array shape", array2.shape)

array3 = np.array([[1,2,3]])
print("array type", type(array3))
print("array shape", array3.shape)

list type <class 'list'>
array type <class 'numpy.ndarray'>
array shape (3,)
array type <class 'numpy.ndarray'>
array shape (2, 3)
array type <class 'numpy.ndarray'>
array shape (1, 3)


## ndarray의 데이터 타입

In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1 , array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
list2 = [1, 2, 'test']
print(type(list2))
array2 = np.array(list2)
print(type(array2))
print(array2 , array2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' 'test'] <U11


In [8]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype(float)
print("array_float: ", array_float, array_float.dtype)

array_float:  [1. 2. 3.] float64


In [10]:
array_int = array_float.astype(int)
print("array_int: ", array_int, array_int.dtype)

array_int:  [1 2 3] int32


## ndarray를 편하게 생성하기 - arange, zeros, ones

In [11]:
sequence_array = np.arange(10)
print("sequence_array: ", sequence_array)
print(sequence_array.dtype, sequence_array.shape)

sequence_array:  [0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [13]:
#(3, 2) shape을 가지는 모든 원소가 0, dtype은 int32 인 ndarray 생성
zeros_arr = np.zeros((3,2), dtype='int32')
print(zeros_arr)
print(zeros_arr.dtype, zeros_arr.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [14]:
# (3, 2) shape을 가지는 모든 원소가 1인 ndarray 생성
ones_arr = np.ones((3,2))
print(ones_arr)
print(ones_arr.dtype, ones_arr.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape

In [15]:
array1 = np.arange(10)
print(array1)

# (2, 5) shape으로 변환
array2 = array1.reshape(2,5)
print(array2)

# (5, 2) shape으로 변환
array3 = array1.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print(array2)

array3 = array1.reshape(5, -1)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
